
# Mirrors src/predictor/bets.py BetStrategyConfig defaults (ASCII labels: firm/upset)
STRATEGY_FIRM_LABEL <- "\u5805"
STRATEGY_UPSET_LABEL <- "\u8352"

STRATEGY_WIN_FAV_ODDS_SKIP <- 3.0
STRATEGY_WIN_UPSET_SCORE_MIN <- 4L
STRATEGY_WIN_PROB_GAP_MAX <- 0.65
STRATEGY_WIN_FAV_SOFT <- 2.5
STRATEGY_FAV_ODDS_UPSET <- 3.0
STRATEGY_UPSET_SCORE_MIN <- 3L
STRATEGY_EXOTIC_HEAD_MIN <- 12L
STRATEGY_EXOTIC_ODDS_STD_MIN <- 88.0
STRATEGY_EXOTIC_CLASS_SCORE_MIN <- 2L
STRATEGY_EXOTIC_DIST_MIN_M <- 1700.0
STRATEGY_EXOTIC_DIST_SCORE_MIN <- 2L
STRATEGY_EXOTIC_UPSET_CLASSES <- c("C1", "C2", "C3", "B2")
STRATEGY_WIN_MAX_PRED_ODDS <- 25.0
STRATEGY_LONGSHOT_MAX_ODDS <- 50.0
