source("r_analysis/config/settings.R", encoding = "UTF-8")
source(file.path(PROJECT_ROOT, "r_analysis", "scripts", "bootstrap.R"), encoding = "UTF-8")
bootstrap_r_analysis()
ensure_output_dirs()
message("Loading master for ROI...")
df <- load_master_filtered()
message("Rows: ", nrow(df))
save_roi_tables(df)
message("Done. See r_analysis/output/tables/roi_*.csv")
