source("r_analysis/config/settings.R", encoding = "UTF-8")
source(file.path(PROJECT_ROOT, "r_analysis", "scripts", "bootstrap.R"), encoding = "UTF-8")
bootstrap_r_analysis()
ensure_output_dirs()
message("Expected value analysis...")
df <- load_master_filtered()
message("Rows: ", nrow(df))
save_expected_value_tables(df)
message("Done. See r_analysis/output/tables/ev_*.csv and output/reports/ev_confidence_guidance.md")
